# Generated by Django 2.1.5 on 2019-02-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('link', models.CharField(max_length=200, unique=True, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='NewMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('small_img_path', models.ImageField(blank=True, upload_to='product_small_img', verbose_name='Миниатюра')),
                ('big_img_path', models.ImageField(blank=True, upload_to='product_big_img', verbose_name='Изображение')),
                ('full_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='mainapp.Category', verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='catalogmenu',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория'),
        ),
    ]
